apiVersion: v2
name: postgres-operator-metrics
description: Metrics Install for Crunchy PostgreSQL Operator
type: application
version: 0.1.0
appVersion: 4.4.3
home: https://github.com/CrunchyData/postgres-operator
icon: https://github.com/CrunchyData/postgres-operator/raw/master/docs/static/logos/pgo.svg
