database:
  CCPImageTag:  centos7-9.6.5-1.6.0
  Port:  5432
  PVCName:  crunchy-pvc
  PGPrimaryUser:  primary
  PGPrimary_Password:  password
  PGUser:  testuser
  PGPassword:  password
  PGDatabase:  userdb
  PGRootPassword:  password
cluster:
  CCPImageTag:  centos7-9.6.5-1.6.0
  Port:  5432
  PVCName:  crunchy-pvc
  PGPrimaryUser:  primary
  PGPrimaryPassword:  password
  PGUser:  testuser
  PGPassword:  password
  PGDatabase:  userdb
  PGRootPassword:  password
  Replicas:  2
