# This file defines the ClusterServiceVersion (CSV) to tell the catalog how to display, create and
# manage the application as a whole. If changes are made to the CRD for this application kind,
# make sure to replace those references below as well.
apiVersion: operators.coreos.com/v1alpha1
kind: ClusterServiceVersion
metadata:
  name: postgresoperator.v3.5.1
  namespace: demo
spec:
  install: 
    strategy: deployment
    spec:
      permissions:
      - serviceAccountName: postgres-operator
        rules:
        - apiGroups:
          - "*"
          resources:
          - "*"
          verbs:
          - "*"
      deployments: 
      - name: postgres-operator
        spec:
          replicas: 1
          selector:
            matchLabels:
              name: postgres-operator
          template:
            metadata:
              labels:
                name: postgres-operator
            spec:
              containers:
                - env:
                  - name: TIMEOUT
                    value: "3600"
                  - name: NAMESPACE
                    valueFrom:
                      fieldRef:
                        apiVersion: v1
                        fieldPath: metadata.namespace
                  name: scheduler
                  image: crunchydata/pgo-scheduler:rhel7-3.5.1
                  imagePullPolicy: IfNotPresent
                  volumeMounts:
                  - mountPath: /pgo-config
                    name: pgo-config
                    readOnly: true
                - env:
                  - name: CRUNCHY_DEBUG
                    value: "true"
                  - name: PORT
                    value: "8443"
                  - name: NAMESPACE
                    valueFrom:
                      fieldRef:
                        apiVersion: v1
                        fieldPath: metadata.namespace
                  name: operator
                  image: crunchydata/postgres-operator:rhel7-3.5.1
                  imagePullPolicy: IfNotPresent
                  volumeMounts:
                  - mountPath: /pgo-config
                    name: pgo-config
                    readOnly: true
                - env:
                  - name: CRUNCHY_DEBUG
                    value: "true"
                  - name: PORT
                    value: "8443"
                  - name: NAMESPACE
                    valueFrom:
                      fieldRef:
                        apiVersion: v1
                        fieldPath: metadata.namespace
                  - name: TLS_NO_VERIFY
                    value: "false"
                  name: apiserver
                  image: crunchydata/pgo-apiserver:rhel7-3.5.1
                  imagePullPolicy: IfNotPresent
                  volumeMounts:
                  - mountPath: /pgo-config
                    name: pgo-config
                    readOnly: true
                  - mountPath: /pgo-auth-secret
                    name: pgo-auth-secret
                    readOnly: true
                  ports:
                  - containerPort: 8443
                    protocol: TCP
              volumes:
              - configMap:
                  defaultMode: 420
                  name: pgo-config
                name: pgo-config
              - name: pgo-auth-secret
                secret:
                  defaultMode: 511
                  secretName: pgo-auth-secret
              restartPolicy: Always
              terminationGracePeriodSeconds: 5
              serviceAccountName: postgres-operator
              serviceAccount: postgres-operator
  customresourcedefinitions:
    owned:
      - description: Represents a Postgres primary cluster member
        displayName: Postgres Primary Cluster Member
        kind: Pgcluster
        name: pgclusters.cr.client-go.k8s.io
        version: v1
        resources:
          - kind: Deployment
            version: v1beta1
          - kind: ReplicaSet
            version: v1beta1
          - kind: Pod
            version: v1
          - kind: Service
            version: v1
        specDescriptors:
          - description: The desired number of member Pods for the deployment.
            displayName: Size
            path: size
            x-descriptors:
              - 'urn:alm:descriptor:com.tectonic.ui:podCount'
        statusDescriptors:
          - description: The current status of the application.
            displayName: Status
            path: phase
            x-descriptors:
              - 'urn:alm:descriptor:io.kubernetes.phase'
          - description: Explanation for the current status of the application.
            displayName: Status Details
            path: reason
            x-descriptors:
              - 'urn:alm:descriptor:io.kubernetes.phase:reason'
      - description: Represents a Postgres replica cluster member
        displayName: Postgres Replica Cluster Member
        kind: Pgreplica
        name: pgreplicas.cr.client-go.k8s.io
        version: v1
        resources:
          - kind: Deployment
            version: v1beta1
          - kind: ReplicaSet
            version: v1beta1
          - kind: Pod
            version: v1
          - kind: Service
            version: v1
        specDescriptors:
          - description: The desired number of member Pods for the deployment.
            displayName: Size
            path: size
            x-descriptors:
              - 'urn:alm:descriptor:com.tectonic.ui:podCount'
        statusDescriptors:
          - description: The current status of the application.
            displayName: Status
            path: phase
            x-descriptors:
              - 'urn:alm:descriptor:io.kubernetes.phase'
          - description: Explanation for the current status of the application.
            displayName: Status Details
            path: reason
            x-descriptors:
              - 'urn:alm:descriptor:io.kubernetes.phase:reason'
      - description: Represents a Postgres sql policy 
        displayName: Postgres SQL Policy
        kind: Pgpolicy
        name: pgpolicies.cr.client-go.k8s.io
        version: v1
        resources:
          - kind: Pgpolicy
            version: v1
        specDescriptors:
          - description: The pgpolicy name.
            displayName: Name
            path: name
            x-descriptors:
              - 'urn:alm:descriptor:com.tectonic.ui:name'
          - description: The pgpolicy sql.
            displayName: SQL
            path: sql
            x-descriptors:
              - 'urn:alm:descriptor:com.tectonic.ui:sql'
        statusDescriptors:
          - description: The current status of the application.
            displayName: Status
            path: phase
            x-descriptors:
              - 'urn:alm:descriptor:io.kubernetes.phase'
          - description: Explanation for the current status of the application.
            displayName: Status Details
            path: reason
            x-descriptors:
              - 'urn:alm:descriptor:io.kubernetes.phase:reason'
      - description: Represents a Postgres workflow task 
        displayName: Postgres workflow task
        kind: Pgtask
        name: pgtasks.cr.client-go.k8s.io
        version: v1
        resources:
          - kind: Pgtask
            version: v1
        specDescriptors:
          - description: The pgtask name.
            displayName: Name
            path: name
            x-descriptors:
              - 'urn:alm:descriptor:com.tectonic.ui:name'
          - description: The pgtask type.
            displayName: TaskType
            path: tasktype
            x-descriptors:
              - 'urn:alm:descriptor:com.tectonic.ui:tasktype'
        statusDescriptors:
          - description: The current status of the application.
            displayName: Status
            path: phase
            x-descriptors:
              - 'urn:alm:descriptor:io.kubernetes.phase'
          - description: Explanation for the current status of the application.
            displayName: Status Details
            path: reason
            x-descriptors:
              - 'urn:alm:descriptor:io.kubernetes.phase:reason'
      - description: Represents a Postgres upgrade task 
        displayName: Postgres upgrade task
        kind: Pgupgrade
        name: pgupgrades.cr.client-go.k8s.io
        version: v1
        resources:
          - kind: Pgupgrade
            version: v1
        specDescriptors:
          - description: The pgupgrade name.
            displayName: Name
            path: name
            x-descriptors:
              - 'urn:alm:descriptor:com.tectonic.ui:name'
          - description: The pgupgrade type.
            displayName: UpgradeType
            path: upgradetype
            x-descriptors:
              - 'urn:alm:descriptor:com.tectonic.ui:upgradetype'
        statusDescriptors:
          - description: The current status of the application.
            displayName: Status
            path: phase
            x-descriptors:
              - 'urn:alm:descriptor:io.kubernetes.phase'
          - description: Explanation for the current status of the application.
            displayName: Status Details
            path: reason
            x-descriptors:
              - 'urn:alm:descriptor:io.kubernetes.phase:reason'
      - description: Represents a Postgres backup task 
        displayName: Postgres backup task
        kind: Pgbackup
        name: pgbackups.cr.client-go.k8s.io
        version: v1
        resources:
          - kind: Pgbackup
            version: v1
        specDescriptors:
          - description: The pgbackup name.
            displayName: Name
            path: name
            x-descriptors:
              - 'urn:alm:descriptor:com.tectonic.ui:name'
          - description: The pgbackup status.
            displayName: BackupStatus
            path: backupstatus
            x-descriptors:
              - 'urn:alm:descriptor:com.tectonic.ui:backupstatus'
        statusDescriptors:
          - description: The current status of the application.
            displayName: Status
            path: phase
            x-descriptors:
              - 'urn:alm:descriptor:io.kubernetes.phase'
          - description: Explanation for the current status of the application.
            displayName: Status Details
            path: reason
            x-descriptors:
              - 'urn:alm:descriptor:io.kubernetes.phase:reason'
  keywords:
    - postgres
    - app
  displayName: Crunchy Postgres Cluster
  provider:
    name: Example
    url: www.crunchydata.com
  maturity: stable
  version: 3.5.1
  maintainers:
    - email: support@crunchydata.com
      name: Crunchy Data
  description: Postgres Cluster on Kubernetes
  labels:
    alm-owner-enterprise-app: postgres-operator
    alm-status-descriptors: postgres-operator.v3.5.1
