apiVersion: postgres-operator.crunchydata.com/v1alpha1
kind: PostgresCluster
metadata:
  name: mycluster
spec:
  instances:
    - name: instance1
  archive:
    pgbackrest:
      image:
      repoHost:
        resources: {}     # (core/v1.ResourceRequirements)
      repoVolume: {} # (VolumeSpec)
