apiVersion: postgres-operator.crunchydata.com/v1beta1
kind: PostgresCluster
metadata:
  name: hippo
spec:
  image: us.gcr.io/container-suite/crunchy-postgres-ha:centos8-13.2-4.7.0-beta.2
  postgresVersion: 12
  instances:
    - name: instance1
      volumeClaimSpec:
        accessModes:
        - "ReadWriteMany"
        resources:
          requests:
            storage: 1Gi
  archive:
    pgbackrest:
      repoHost:
        dedicated: {}
        image: us.gcr.io/container-suite/crunchy-pgbackrest:centos8-13.2-4.7.0-beta.2
      repos:
      - name: repo1
        volume:
          volumeClaimSpec:
            accessModes:
            - "ReadWriteMany"
            resources:
              requests:
                storage: 1Gi
      - name: repo2
        volume:
          volumeClaimSpec:
            accessModes:
            - "ReadWriteMany"
            resources:
              requests:
                storage: 1Gi
  proxy:
    pgBouncer:
      image: us.gcr.io/container-suite/crunchy-pgbouncer:centos8-13.2-4.7.0-beta.2
