{{ if .Values.rbac.create }}
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: {{ template "postgres-operator.fullname" . }}
  labels:
    app: {{ template "postgres-operator.name" . }}
    chart: {{ template "postgres-operator.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ template "postgres-operator.fullname" . }}
subjects:
- kind: ServiceAccount
  name: {{ template "postgres-operator.serviceAccountName" . }}
  namespace: "{{ .Release.Namespace }}"
{{ end }}
