apiVersion: v1
kind: ConfigMap
metadata:
  name: pgo-pgbackrest-config
  labels:
    app: {{ template "postgres-operator.name" . }}
    chart: {{ template "postgres-operator.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
data:
{{ (.Files.Glob "files/postgres-operator/pgbackrest.conf*").AsConfig | indent 2 }}
