{{ if .Values.rbac.create }}
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: RoleBinding
metadata:
  name: {{ template "postgres-operator.namespaceRoleName" . }}
  namespace: "{{ .Release.Namespace }}"
  labels:
    app: {{ template "postgres-operator.name" . }}
    chart: {{ template "postgres-operator.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ template "postgres-operator.namespaceRoleName" . }}
subjects:
- kind: ServiceAccount
  name: {{ template "postgres-operator.serviceAccountName" . }}
  namespace: "{{ .Release.Namespace }}"
{{ end }}