apiVersion: v1
kind: Service
metadata:
  labels:
    app: "{{ template "name" . }}"
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
  name: {{ template "fullname" . }}
spec:
  type: "ClusterIP"
  ports:
    - name: apiserver
      port: 8443
      protocol: TCP
      targetPort: 8443
      nodePort: 0
  selector:
    name: postgres-operator
    release: {{ .Release.Name }}
