KUBECONFIG:  /etc/kubernetes/admin.conf
NAMESPACE:  default
DB:
  CCP_IMAGE_TAG:  centos7-9.6-1.4.1
  PORT:  5432
  PG_MASTER_USER:  master
  PG_MASTER_PASSWORD:  password
  PG_USER:  testuser
  PG_PASSWORD:  password
  PG_DATABASE:  userdb
  PG_ROOT_PASSWORD:  password
  PVC_NAME:  crunchy-pvc
  PVC_SIZE:  100M
  PVC_ACCESS_MODE:  ReadWriteMany
  FSGROUP:  26
  SUPPLEMENTALGROUPS:  65534
  STRATEGY:  1
PGO:
  LSPVC_TEMPLATE:  /home/jeffmc/.pgo.lspvc-template.json
  CO_IMAGE_TAG:  centos7-1.2.0
  DEBUG:  false
CLUSTER:
  REPLICAS:  2
  STRATEGY:  1
