KUBECONFIG:  /etc/kubernetes/admin.conf
NAMESPACE:  default
CLUSTER:
  CCP_IMAGE_TAG:  centos7-9.6-1.4.1
  PORT:  5432
  PG_MASTER_USER:  master
  PG_MASTER_PASSWORD:  password
  PG_USER:  testuser
  PG_PASSWORD:  password
  PG_DATABASE:  userdb
  PG_ROOT_PASSWORD:  password
  STRATEGY:  1
  REPLICAS:  0
MASTER_STORAGE:
  PVC_NAME:  crunchy-pvc
  STORAGE_CLASS:  standard
  PVC_ACCESS_MODE:  ReadWriteMany
  PVC_SIZE:  100M
  STORAGE_TYPE:  emptydir
REPLICA_STORAGE:
  PVC_NAME:  crunchy-pvc
  STORAGE_CLASS:  standard
  PVC_ACCESS_MODE:  ReadWriteMany
  PVC_SIZE:  100M
  STORAGE_TYPE:  emptydir
PGO:
  LSPVC_TEMPLATE:  /home/jeffmc/.pgo.lspvc-template.json
  CO_IMAGE_TAG:  centos7-1.3.2
  DEBUG:  false
