COImagePrefix:  crunchydata
COImageTag:  centos7-2.5
DbDatabase:  userdb
DbUser:  postgres
DbPort:  5432
TableToLoad:  xraycsvtable
FilePath:  sample.csv
FileType:  csv
PVCName:  crunchy-pvc
SecurityContext:  
