namespace: postgres-operator

commonLabels:
  postgres-operator.crunchydata.com/control-plane: postgres-operator

bases:
- ../crd
- ../rbac/namespace
- ../manager

patches:
- manager-target.yaml

images:
- name: postgres-operator
  newName: gcr.io/crunchy-dev-test/postgres-operator
  newTag: centos8-v1beta1
